package com.ecommerce.model;

public enum ErrorCode {
    INSUFFICIENT_PRODUCT_QUANTITY,
    ORDER_CREATION_FAILED,
    PRODUCT_CREATION_FAILED,
    PRODUCT_ALREADY_EXIST,
    PINCODE_SERVICE_UNAVAILABILITY,
    BUYER_CREATION_FAILED
}

